# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.provider "virtualbox"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.define "fSMDtrusty64" do |fSMDtrusty64|
      fSMDtrusty64.vm.box = "ubuntu/trusty64"
      fSMDtrusty64.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
      fSMDtrusty64.vm.hostname = "fSMDtrusty64"
      fSMDtrusty64.vm.network "private_network", ip: "192.168.77.20"
      fSMDtrusty64.vm.provider "virtualbox" do |vb|
        vb.name= "fSMDtrusty64"
        # TODO: further settings as amount of cores
      end
      fSMDtrusty64.vm.provision "ansible" do |ansible|
          ansible.groups = {
              "ubuntu" => [
                  "fSMDtrusty64"
              ]
          }
          ansible.playbook = "../../ansible/main.yml"
      end
  end

  # shared folders do often lead to problems with the virtual machine version
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.forward_x11 = "true"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

end
